bdkurs/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]


urlpatterns += [
    path('', RedirectView.as_view(url='/afisha/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

from .views import EventDetailView, PlaceDetailView, ArtistDetailView, OrgDetailView

urlpatterns = [
	re_path(r'^afisha/$', views.index, name='index'),
    re_path(r'^artists/$', views.artists, name='artists'),
    re_path(r'^places/$', views.places, name='places'),
    re_path(r'^orgs/$', views.orgs, name='orgs'),
	path('afisha/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
	path('places/<int:pk>/', PlaceDetailView.as_view(), name='place-detail'),
	path('artists/<int:pk>/', ArtistDetailView.as_view(), name='artist-detail'),
	path('orgs/<int:pk>/', OrgDetailView.as_view(), name='artist-detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

class Tag(models.Model):
	name = models.CharField(max_length=200, unique=True)
	def __str__(self):
		return self.name

class Place(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	link = models.URLField()
	address = models.CharField(max_length=200)
	image = models.ImageField(upload_to='places', default='/')

	def __str__(self):
		return self.name


class Org(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	link = models.URLField()
	tags = models.ManyToManyField(Tag)
	image = models.ImageField(upload_to='orgs', default='/')

	def __str__(self):
		return self.name

class Artist(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	link = models.URLField()
	tags = models.ManyToManyField(Tag)
	image = models.ImageField(upload_to='artists', default='/')
	def __str__(self):
		return self.name

class Event(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	
	CONCERT = 'CON'
	FESTIVAL = 'FES'
	LECTION = 'LEC'
	EXPO = 'EXP'
	FORUM = 'FOR'
	OTHER = 'OTH'

	EVENT_CHOICES = [
		(CONCERT, 'Концерт'),
		(FESTIVAL, 'Фестиваль'),
		(LECTION, 'Лекция'),
		(EXPO, 'Выставка'),
		(FORUM, 'Форум'),
		(OTHER, 'Другое'),
	]

	event_type = models.CharField(
		max_length=3,
		choices=EVENT_CHOICES,
		default=CONCERT,
	)
	
	price = models.IntegerField()
	link = models.URLField()

	datetime = models.DateTimeField()
	artists = models.ManyToManyField(Artist)
	org = models.ManyToManyField(Org)
	place = models.ForeignKey('Place', on_delete=models.CASCADE)
	tags = models.ManyToManyField(Tag)

	image = models.ImageField(upload_to='events', default='/')
	
	def get_day(self):
		t = str(self.datetime.day)
		if len(t) == 1:
			t = '0'+t
		return t

	def get_month(self):
		t = ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря']
		return t[self.datetime.month-1]
	
	def get_week_day(self):
		t = ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье']
		return t[self.datetime.weekday()]
	def get_tags(self):
		return self.tags.all()

	def __str__(self):
		return self.name
	

mainapp/forms.py
from django import forms
import urllib

class EventForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Название'}), required=False)
    date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control mb-3 choosedate', 'placeholder': 'Дата'}), required=False)
    price_from = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'от'}), required=False)
    price_to = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'до'}), required=False)
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'напр.: инди'}), required=False)

class ArtistForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Имя/название'}), required=False)
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'напр.: инди'}), required=False)


class OrgForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Имя/название'}), required=False)
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'напр.: инди'}), required=False)

class PlaceForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Имя/название'}), required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Адрес'}), required=False)
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'напр.: клуб, лекторий'}), required=False)

mainapp/views.py
from django.shortcuts import render
from .models import Place, Event, Artist, Org
from django.views.generic.detail import DetailView
from .forms import EventForm, ArtistForm, OrgForm, PlaceForm


def index(request):
	name = request.GET.get('name', '')
	date = request.GET.get('date', '')
	price_from = request.GET.get('price_from', '')
	price_to = request.GET.get('price_to', '')
	tags = request.GET.get('tags', '')
	
	events = Event.objects.all()
	

	if name != '':
		events = events.filter(name__icontains=name)

	if date != '':
		events = events.filter(datetime__date=date)
	
	if price_from != '' and price_from.isdigit():
		events = events.filter(price__gte=price_from)

	if price_to != '' and price_to.isdigit():
		events = events.filter(price__lte=price_to)

	tags = tags.split()


	if tags != '':
		for tag in tags:
			events = events.filter(tags__name__iexact=tag)
	
	events = events.order_by('datetime')

	empty_flag = False
	if len(events) == 0:
		empty_flag = True


	form = EventForm(request.GET)
	return render(request,
        'index.html',
        context={'events': events, 'empty_flag': empty_flag, 'form': form})

def artists(request):
	name = request.GET.get('name', '')
	tags = request.GET.get('tags', '')

	a = Artist.objects.all()
	
	if name != '':
		a = a.filter(name__icontains=name)

	tags = tags.split()

	if tags != '':
			for tag in tags:
				a = a.filter(tags__name__iexact=tag)	

	empty_flag = False
	if len(a) == 0:
		empty_flag = True
	
	form = ArtistForm(request.GET)

	return render(request,
        'artists.html',
        context={'artists': a, 'empty_flag': empty_flag, 'form': form})

def orgs(request):
	name = request.GET.get('name', '')
	tags = request.GET.get('tags', '')

	o = Org.objects.all()

	if name != '':
		o = o.filter(name__icontains=name)

	tags = tags.split()

	if tags != '':
			for tag in tags:
				o = o.filter(tags__name__iexact=tag)	

	empty_flag = False
	if len(o) == 0:
		empty_flag = True
	
	form = OrgForm(request.GET)
	return render(request,
        'orgs.html',
        context={'orgs': o, 'empty_flag': empty_flag, 'form': form})

def places(request):
	name = request.GET.get('name', '')
	address = request.GET.get('address', '')
	tags = request.GET.get('tags', '')

	p = Place.objects.all()

	if name != '':
		p = p.filter(name__icontains=name)

	if address != '':
		a_s = address.split()
		for it in a_s:
			p = p.filter(address__icontains=it)
	
	tags = tags.split()

	if tags != '':
			for tag in tags:
				p = p.filter(tags__name__iexact=tag)
	

	empty_flag = False
	if len(p) == 0:
		empty_flag = True
	
	form = PlaceForm(request.GET)

	return render(request,
        'places.html',
        context={'places': p, 'empty_flag': empty_flag, 'form': form})




class EventDetailView(DetailView):
	model = Event

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['artists'] = self.get_object().artists.all()
		context['orgs'] = self.get_object().org.all()
		context['tags'] = self.get_object().tags.all()
		return context


class PlaceDetailView(DetailView):
	model = Place

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['events'] = self.get_object().event_set.all().order_by('datetime')
		return context


class OrgDetailView(DetailView):
	model = Org


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['events'] = self.get_object().event_set.all().order_by('datetime')
		return context

class ArtistDetailView(DetailView):
	model = Artist


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['events'] = self.get_object().event_set.all().order_by('datetime')
		context['tags'] = self.get_object().tags.all()
		return context

mainapp/templates/mainapp/artist_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link href="{% static 'css/a_date.css' %}" rel="stylesheet">

<div class="container-fluid cov" style=
"background-image:linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), 
url(/media/{{ artist.image }});">
	<div class="container covertext">
		<p class="text-white h4"> {%for tag in tags %} {{tag.name}} {%endfor%} </p>
		<h1 class="display-1 font-weight-bold text-white">{{artist.name}}</h1>
		<a href="{{artist.link}}" class="btn btn-outline-warning btn-lg font-weight-bold" style="border-radius: 32px; margin-top:20px;">Перейти на сайт</a>
	</div>
</div>

<div class = "container">
	<div class = "row">
		<div class="container eventtext">
			<div class="col">
				<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Об исполнителе</h1>
				<p> {{artist.description}} </p>
				<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Ближайшие события</h1>
				<div class="container">
					{%for event in events %}
					<div class="container">
						<div class="row border-bottom mt-3">
							<div class="col-3">
								<div class="gray_small"> {% for tag in event.tags.all %} {{tag.name}} {% endfor %} </div>
								 <a href="/afisha/{{ event.pk }}/" class="divLink"><h4> {{event.name}}</h4> </a> 
							</div>
							<div class="col-3">
							<div class="a_date my-0">{{event.get_day}}</div>
							<div class="a_day">{{ event.get_week_day }}</div>
							<div class="a_month">{{event.get_month }}</div>
							</div>
							<div class="col-3">
							<a href="/places/{{ event.place.pk }}/" class="divLink"><h3 class="mb-0"> {{event.place}}</h3> </a> 
							<p class="gray_small">{{event.place.address}}</p>
							</div>
							<div class="col-3">
							<a href="/afisha/{{ event.pk }}/" class="btn btn-lg btn-block btn-outline-warning">от {{event.price}}₽</a>
							</div>
						</div>
					</div>
				{% endfor %}
				</div>


			</div>
		</div>
	</div>
</div>

{% endblock %}

mainapp/templates/mainapp/event_detail.html
{% extends "base.html" %}
{% load static %}

<link href="{% static 'css/event_detail.css' %}" rel="stylesheet">
<link href="{% static 'css/a_date.css' %}" rel="stylesheet">
{% block content %}

<div class="container-fluid cov" style=
"background-image:linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), 
url(/media/{{ event.image }});">
	<div class="container covertext">
		<p class="text-white h4">{{event.get_event_type_display}} | {{event.datetime}}  | {% for tag in event.tags.all %}{{tag.name}} {% endfor %}</p>
		<h1 class="display-1 font-weight-bold text-white">{{event.name}}</h1>
		<h2 class="text-white font-weight-bold"><a href="/places/{{event.place.pk}}" class="placelink"> @ {{event.place}} </a></h2>
		<a href="{{event.link}}" class="btn btn-outline-warning btn-lg font-weight-bold" style="border-radius: 32px; margin-top:20px;">Купить билеты</a>
	</div>
</div>

<div class = "container">
<div class = "row">
<div class="container eventtext">
	<div class="col">
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">О мероприятии</h1>
		<p> {{event.description}} </p>
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Артисты</h1>
		<div class="col">
			<div class="row">
				{% for artist in artists %}
				
				<div class="col-md-4">
					<a href="/artists/{{ artist.pk }}/" class="divLink">
					<div class="card mb-4 border-white">
						<img class="card-img-top rounded"src= "/media/{{ artist.image }}" width=340 height=220 style="object-fit: cover;"><title> {{ artist.name }} </title>
						<div class="card-body" style="padding-left: 5px">
							<h3 class="card-title font-weight-bold" style="margin-bottom:0px"> {{ artist.name }} </h3>
							<div class="d-flex justify-content-between align-items-center">
							<div class="text-muted gray_small mt0"> {% for tag in artist.tags.all %} {{tag.name}} {% endfor %} </div>
							</div>
						</div>
					</div>
					</a>
				</div>
        
        {% endfor %}

			</div>
		</div>

		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Организаторы</h1>
		<div class="col">
			<div class="row">
				{% for org in orgs %}
        
				<div class="col-md-4">
					<a href="/orgs/{{ org.pk }}/" class="divLink">
					<div class="card mb-4 border-white">
						<img class="card-img-top rounded" width=340 height=220 style="object-fit: cover;" src= "/media/{{ org.image }}"><title> {{ org.name }} </title>
					<div class="card-body" style="padding-left: 5px">
						<h3 class="card-title font-weight-bold" style="margin-bottom:0px;"> {{ org.name }} </h3>
						<div class="d-flex justify-content-between align-items-center">
							<div class="text-muted gray_small mt0"> {% for tag in org.tags.all %} {{tag.name}} {% endfor %} </div>
						</div>
					</div>
					</div>
					</a>
				</div>
        
        		{% endfor %}

			</div>
		</div>

	</div>
</div>
</div>
</div>

{% endblock %}

mainapp/templates/mainapp/org_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link href="{% static 'css/a_date.css' %}" rel="stylesheet">
<div class="container-fluid cov" style=
"background-image:linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), 
url(/media/{{ org.image }});">
	<div class="container covertext">
		<p class="text-white font-weight-bold"> </p>
		<h1 class="display-1 font-weight-bold text-white">{{org.name}}</h1>
		<a href="{{org.link}}" class="btn btn-outline-warning btn-lg font-weight-bold" style="border-radius: 32px; margin-top:20px;">Перейти на сайт</a>
	</div>
</div>

<div class = "container">
<div class = "row">
<div class="container eventtext">
	<div class="col">
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Об организаторе</h1>
		<p> {{org.description}} </p>
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Ближайшие события</h1>
				<div class="container">
				{%for event in events %}
					<div class="container">
						<div class="row border-bottom mt-3">
							<div class="col-3">
								<div class="gray_small"> {% for tag in event.tags.all %} {{tag.name}} {% endfor %} </div>
								 <a href="/afisha/{{ event.pk }}/" class="divLink"><h4> {{event.name}}</h4> </a> 
							</div>
							<div class="col-3">
							<div class="a_date my-0">{{event.get_day}}</div>
							<div class="a_day">{{ event.get_week_day }}</div>
							<div class="a_month">{{event.get_month }}</div>
							</div>
							<div class="col-3">
							<a href="/places/{{ event.place.pk }}/" class="divLink"><h3 class="mb-0"> {{event.place}}</h3> </a> 
							<p class="gray_small">{{event.place.address}}</p>
							</div>
							<div class="col-3">
							<a href="/afisha/{{ event.pk }}/" class="btn btn-lg btn-block btn-outline-warning">от {{event.price}}₽</a>
							</div>
						</div>
					</div>
				{% endfor %}
				</div>
	</div>
</div>
</div>
</div>

{% endblock %}

mainapp/templates/mainapp/place_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<link href="{% static 'css/a_date.css' %}" rel="stylesheet">
<div class="container-fluid cov" style=
"background-image:linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), 
url(/media/{{ place.image }});">
	<div class="container covertext">
		<p class="text-white h4"></p>
		<h1 class="display-1 font-weight-bold text-white">{{place.name}}</h1>
		<h2 class="text-white font-weight-bold">{{place.address}}</h2>
		<a href="{{place.link}}" class="btn btn-outline-warning btn-lg font-weight-bold" style="border-radius: 32px; margin-top:20px;">Перейти на сайт</a>
	</div>
</div>

<div class = "container">
<div class = "row">
<div class="container eventtext">
	<div class="col">
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">О месте</h1>
		<p> {{place.description}} </p>
		<h1 class="font-weight-bold display-4" style="padding-bottom: 20px">Афиша</h1>
				
				{%for event in events %}
					<div class="container">
						<div class="row border-bottom mt-3">
							<div class="col-3">
								<div class="gray_small"> {% for tag in event.tags.all %} {{tag.name}} {% endfor %} </div>
								 <a href="/afisha/{{ event.pk }}/" class="divLink"><h4> {{event.name}}</h4> </a> 
							</div>
							<div class="col-3">
							<div class="a_date my-0">{{event.get_day}}</div>
							<div class="a_day">{{ event.get_week_day }}</div>
							<div class="a_month">{{event.get_month }}</div>
							</div>
							<div class="col-3">
							<a href="/places/{{ event.place.pk }}/" class="divLink"><h3 class="mb-0"> {{event.place}}</h3> </a> 
							<p class="gray_small">{{event.place.address}}</p>
							</div>
							<div class="col-3">
							<a href="/afisha/{{ event.pk }}/" class="btn btn-lg btn-block btn-outline-warning">от {{event.price}}₽</a>
							</div>
						</div>
					</div>
				{% endfor %}
	</div>
</div>
</div>
</div>

{% endblock %}